/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.heimen.gas_mixer;

/**
 *
 * @author Ole
 */
public class CalcFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcFrame
     */
    public CalcFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        currentMixPanel = new javax.swing.JPanel();
        currentPressureField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentOxygenField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        currentHeliumField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        desiredMixPanel = new javax.swing.JPanel();
        targetPressureField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        targetOxygenField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        targetHeliumField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        currentMixPanel2 = new javax.swing.JPanel();
        cylinderSizeField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        currentMixPanel3 = new javax.swing.JPanel();
        heliumNeededField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        oxygenNeededField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        topMixNeededField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        errorPanel = new javax.swing.JPanel();
        errorFieldTop = new javax.swing.JTextField();
        errorFieldTop1 = new javax.swing.JTextField();
        currentMixPanel4 = new javax.swing.JPanel();
        topMixOxygenField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 510));
        setPreferredSize(new java.awt.Dimension(500, 510));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentMixPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current gas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        currentMixPanel.setMinimumSize(new java.awt.Dimension(227, 148));
        currentMixPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentPressureField.setText("0");
        currentPressureField.setPreferredSize(new java.awt.Dimension(54, 22));
        currentPressureField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                currentPressureFieldFocusLost(evt);
            }
        });
        currentPressureField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                currentPressureFieldKeyReleased(evt);
            }
        });
        currentMixPanel.add(currentPressureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 24, 54, 22));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Pressure");
        currentMixPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 27, 67, -1));

        jLabel2.setText("bar");
        currentMixPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 27, -1, -1));

        currentOxygenField.setText("21");
        currentOxygenField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                currentOxygenFieldFocusLost(evt);
            }
        });
        currentOxygenField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                currentOxygenFieldKeyReleased(evt);
            }
        });
        currentMixPanel.add(currentOxygenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 52, 54, 22));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Oxygen");
        currentMixPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 55, 67, -1));

        jLabel4.setText("%");
        currentMixPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 55, 17, -1));

        jLabel7.setText("%");
        currentMixPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 83, 17, -1));

        currentHeliumField.setText("35");
        currentHeliumField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                currentHeliumFieldFocusLost(evt);
            }
        });
        currentHeliumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentHeliumFieldActionPerformed(evt);
            }
        });
        currentHeliumField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                currentHeliumFieldKeyReleased(evt);
            }
        });
        currentMixPanel.add(currentHeliumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 80, 54, 22));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Helium");
        currentMixPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 83, 67, -1));

        getContentPane().add(currentMixPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 230, 120));

        desiredMixPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Target gas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        desiredMixPanel.setMaximumSize(new java.awt.Dimension(227, 148));
        desiredMixPanel.setMinimumSize(new java.awt.Dimension(227, 148));
        desiredMixPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        targetPressureField.setText("220");
        targetPressureField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                targetPressureFieldFocusLost(evt);
            }
        });
        targetPressureField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                targetPressureFieldKeyReleased(evt);
            }
        });
        desiredMixPanel.add(targetPressureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 24, 54, 22));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Pressure");
        desiredMixPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 27, 67, -1));

        jLabel6.setText("bar");
        desiredMixPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 27, -1, -1));

        targetOxygenField.setText("21");
        targetOxygenField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                targetOxygenFieldFocusLost(evt);
            }
        });
        targetOxygenField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                targetOxygenFieldKeyReleased(evt);
            }
        });
        desiredMixPanel.add(targetOxygenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 52, 54, 22));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Oxygen");
        desiredMixPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 55, 67, -1));

        jLabel10.setText("%");
        desiredMixPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 55, 17, -1));

        jLabel11.setText("%");
        desiredMixPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 83, 17, -1));

        targetHeliumField.setText("35");
        targetHeliumField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                targetHeliumFieldFocusLost(evt);
            }
        });
        targetHeliumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetHeliumFieldActionPerformed(evt);
            }
        });
        targetHeliumField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                targetHeliumFieldKeyReleased(evt);
            }
        });
        desiredMixPanel.add(targetHeliumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 80, 54, 22));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Helium");
        desiredMixPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 83, 67, -1));

        getContentPane().add(desiredMixPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 6, 230, 120));

        currentMixPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cylinder size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        currentMixPanel2.setMaximumSize(new java.awt.Dimension(227, 64));
        currentMixPanel2.setMinimumSize(new java.awt.Dimension(227, 64));
        currentMixPanel2.setPreferredSize(new java.awt.Dimension(227, 64));
        currentMixPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cylinderSizeField.setText("24");
        cylinderSizeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cylinderSizeFieldFocusLost(evt);
            }
        });
        cylinderSizeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cylinderSizeFieldKeyReleased(evt);
            }
        });
        currentMixPanel2.add(cylinderSizeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 24, 54, 22));

        jLabel16.setText("l");
        currentMixPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 27, 17, -1));

        getContentPane().add(currentMixPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 137, -1, 63));

        currentMixPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filling instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        currentMixPanel3.setMaximumSize(new java.awt.Dimension(227, 107));
        currentMixPanel3.setMinimumSize(new java.awt.Dimension(227, 107));
        currentMixPanel3.setPreferredSize(new java.awt.Dimension(227, 107));
        currentMixPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heliumNeededField.setText("0");
        heliumNeededField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        heliumNeededField.setEnabled(false);
        currentMixPanel3.add(heliumNeededField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 18, 54, 22));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Helium");
        currentMixPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 21, 67, -1));

        jLabel14.setText("bar");
        currentMixPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 21, -1, -1));

        jLabel17.setText("bar");
        currentMixPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 49, -1, -1));

        oxygenNeededField.setText("0");
        oxygenNeededField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        oxygenNeededField.setEnabled(false);
        currentMixPanel3.add(oxygenNeededField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 46, 54, 22));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("Oxygen");
        currentMixPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 49, 67, -1));

        jLabel18.setText("bar");
        currentMixPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 77, -1, -1));

        topMixNeededField.setText("0");
        topMixNeededField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        topMixNeededField.setEnabled(false);
        currentMixPanel3.add(topMixNeededField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 74, 54, 22));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("Top-up");
        currentMixPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 77, 67, -1));

        getContentPane().add(currentMixPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 240, 230, 120));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 472, 10));

        jButton1.setText("calculate");
        jButton1.setMaximumSize(new java.awt.Dimension(227, 32));
        jButton1.setMinimumSize(new java.awt.Dimension(227, 32));
        jButton1.setPreferredSize(new java.awt.Dimension(227, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 380, 230, 32));

        errorPanel.setMaximumSize(new java.awt.Dimension(227, 107));
        errorPanel.setMinimumSize(new java.awt.Dimension(227, 107));
        errorPanel.setPreferredSize(new java.awt.Dimension(227, 107));
        errorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorFieldTop.setEditable(false);
        errorFieldTop.setForeground(new java.awt.Color(255, 0, 0));
        errorFieldTop.setText("error2");
        errorFieldTop.setBorder(null);
        errorPanel.add(errorFieldTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, -1));

        errorFieldTop1.setEditable(false);
        errorFieldTop1.setForeground(new java.awt.Color(255, 0, 0));
        errorFieldTop1.setText("error");
        errorFieldTop1.setBorder(null);
        errorPanel.add(errorFieldTop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        getContentPane().add(errorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        currentMixPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Top-up mix", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        currentMixPanel4.setMaximumSize(new java.awt.Dimension(227, 64));
        currentMixPanel4.setMinimumSize(new java.awt.Dimension(227, 64));
        currentMixPanel4.setPreferredSize(new java.awt.Dimension(227, 64));
        currentMixPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topMixOxygenField.setText("21");
        topMixOxygenField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                topMixOxygenFieldFocusLost(evt);
            }
        });
        topMixOxygenField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                topMixOxygenFieldKeyReleased(evt);
            }
        });
        currentMixPanel4.add(topMixOxygenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 24, 54, 22));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("Oxygen");
        currentMixPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 27, 67, -1));

        jLabel23.setText("%");
        currentMixPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 27, 17, -1));

        getContentPane().add(currentMixPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, 230, 63));

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Standard gases");

        jMenuItem2.setText("21/35");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("18/45");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("15/55");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("10/70");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentHeliumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentHeliumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentHeliumFieldActionPerformed

    private void targetHeliumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetHeliumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetHeliumFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double cylinderSize = Double.parseDouble(cylinderSizeField.getText());
        double currentPressure = Double.parseDouble(currentPressureField.getText());
        double currentOxygen = Double.parseDouble(currentOxygenField.getText());
        double currentHelium = Double.parseDouble(currentHeliumField.getText());
        double topMixOxygen = Double.parseDouble(topMixOxygenField.getText());

        double targetOxygen = Double.parseDouble(targetOxygenField.getText());
        double targetHelium = Double.parseDouble(targetHeliumField.getText());
        double targetPressure = Double.parseDouble(targetPressureField.getText());

        GasParameter params = new GasParameter(
                cylinderSize,
                currentPressure,
                currentOxygen,
                currentHelium,
                topMixOxygen,
                targetOxygen,
                targetHelium,
                targetPressure
        );

        GasMix mix = new GasMix(params);
        int[] calculatedGases = mix.getMix();
        topMixNeededField.setText(String.valueOf(calculatedGases[0]));
        heliumNeededField.setText(String.valueOf(calculatedGases[1]));
        oxygenNeededField.setText(String.valueOf(calculatedGases[2]));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void currentPressureFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentPressureFieldFocusLost
        // TODO add your handling code here:
        // VALIDATE PRESSURE
    }//GEN-LAST:event_currentPressureFieldFocusLost

    private void currentOxygenFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentOxygenFieldFocusLost
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_currentOxygenFieldFocusLost

    private void currentHeliumFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentHeliumFieldFocusLost
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_currentHeliumFieldFocusLost

    private void targetPressureFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_targetPressureFieldFocusLost
        // TODO add your handling code here:
        // VALIDATE PRESSURE
    }//GEN-LAST:event_targetPressureFieldFocusLost

    private void targetOxygenFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_targetOxygenFieldFocusLost
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_targetOxygenFieldFocusLost

    private void targetHeliumFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_targetHeliumFieldFocusLost
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_targetHeliumFieldFocusLost

    private void currentPressureFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentPressureFieldKeyReleased
        // TODO add your handling code here:
        // VALIDATE PRESSURE
    }//GEN-LAST:event_currentPressureFieldKeyReleased

    private void currentOxygenFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentOxygenFieldKeyReleased
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_currentOxygenFieldKeyReleased

    private void currentHeliumFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentHeliumFieldKeyReleased
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_currentHeliumFieldKeyReleased

    private void targetPressureFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_targetPressureFieldKeyReleased
        // TODO add your handling code here:
        // VALIDATE PRESSURE
    }//GEN-LAST:event_targetPressureFieldKeyReleased

    private void targetOxygenFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_targetOxygenFieldKeyReleased
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_targetOxygenFieldKeyReleased

    private void targetHeliumFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_targetHeliumFieldKeyReleased
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_targetHeliumFieldKeyReleased

    private void cylinderSizeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cylinderSizeFieldKeyReleased
        // TODO add your handling code here:
        // VALIDATE PRESSURE
    }//GEN-LAST:event_cylinderSizeFieldKeyReleased

    private void cylinderSizeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cylinderSizeFieldFocusLost
        // TODO add your handling code here:
        // VALIDATE PERCENTAGE
    }//GEN-LAST:event_cylinderSizeFieldFocusLost

    private void topMixOxygenFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_topMixOxygenFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_topMixOxygenFieldFocusLost

    private void topMixOxygenFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_topMixOxygenFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_topMixOxygenFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentHeliumField;
    private javax.swing.JPanel currentMixPanel;
    private javax.swing.JPanel currentMixPanel2;
    private javax.swing.JPanel currentMixPanel3;
    private javax.swing.JPanel currentMixPanel4;
    private javax.swing.JTextField currentOxygenField;
    private javax.swing.JTextField currentPressureField;
    private javax.swing.JTextField cylinderSizeField;
    private javax.swing.JPanel desiredMixPanel;
    private javax.swing.JTextField errorFieldTop;
    private javax.swing.JTextField errorFieldTop1;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JTextField heliumNeededField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField oxygenNeededField;
    private javax.swing.JTextField targetHeliumField;
    private javax.swing.JTextField targetOxygenField;
    private javax.swing.JTextField targetPressureField;
    private javax.swing.JTextField topMixNeededField;
    private javax.swing.JTextField topMixOxygenField;
    // End of variables declaration//GEN-END:variables
}
